# Generated by Django 2.0.6 on 2019-03-01 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181203_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_start', models.DateTimeField(auto_now_add=True)),
                ('promotion_end', models.DateTimeField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_projects', to='projects.Project')),
            ],
        ),
    ]
