# Generated by Django 2.0.6 on 2019-03-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_promotedproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotedproject',
            old_name='promotion_start',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='promotedproject',
            name='promotion_end',
        ),
    ]
