# Generated by Django 2.0.6 on 2019-03-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_promotedproject_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotedproject',
            name='end',
        ),
    ]
