# Generated by Django 2.0.6 on 2019-03-01 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_promotedproject_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedproject',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
