# Generated by Django 2.0.6 on 2019-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_promotionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsettings',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='promotionsettings',
            name='display_amount',
            field=models.IntegerField(default=1),
        ),
    ]
