# Generated by Django 2.0.6 on 2019-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190308_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requested_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
