# Generated by Django 2.0.6 on 2019-03-15 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190308_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='promotedproject',
            name='end',
            field=models.DateTimeField(blank=True, default=projects.models.PromotedProject.get_default_end_date),
        ),
        migrations.AlterField(
            model_name='promotedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_project', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='promotedproject',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activepromotion',
            name='promoted_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_promotion', to='projects.PromotedProject'),
        ),
    ]
