# Generated by Django 2.0.6 on 2019-03-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190315_0422'),
        ('projects', '0014_project_requested_promotion'),
    ]

    operations = [
    ]
