# Generated by Django 2.0.6 on 2019-03-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge_20190315_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requested_promotion',
        ),
    ]
