# Generated by Django 2.0.6 on 2019-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_requested_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requested_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
