# Generated by Django 2.0.6 on 2019-03-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190315_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepromotion',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
            preserve_default=False,
        ),
    ]
