# Generated by Django 2.0.6 on 2019-03-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_activepromotion_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activepromotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='activepromotion',
            name='promoted_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.PromotedProject'),
        ),
    ]
