# Generated by Django 2.0.6 on 2019-03-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_full_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
