# Generated by Django 2.0.6 on 2019-03-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_display_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_full_name',
            field=models.BooleanField(default=True),
        ),
    ]
