# Generated by Django 2.0.6 on 2019-03-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190306_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_phone_name',
            new_name='display_phone',
        ),
    ]
