# Generated by Django 2.0.6 on 2019-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190303_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_email_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_last_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_phone_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_street',
            field=models.BooleanField(default=True),
        ),
    ]
