# Generated by Django 2.0.6 on 2019-03-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190303_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_email_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_phone_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_street',
        ),
    ]
