# Generated by Django 2.0.6 on 2019-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190303_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_full_name',
            field=models.BooleanField(default=True),
        ),
    ]
