# Generated by Django 2.0.6 on 2019-03-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewText',
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=None, max_length=1500),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
