# Generated by Django 2.0.6 on 2019-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190303_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_country',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_email_name',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_last_name',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_phone_name',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_street',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_full_name',
            field=models.NullBooleanField(default=True),
        ),
    ]
