# Generated by Django 2.0.6 on 2019-03-10 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190310_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 13, 4, 39, 51372, tzinfo=utc)),
        ),
    ]
