# Generated by Django 2.0.6 on 2019-03-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190303_1054'),
        ('user', '0005_auto_20190306_1018'),
    ]

    operations = [
    ]
