# Generated by Django 2.0.6 on 2019-03-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190311_0817'),
        ('user', '0014_auto_20190311_1014'),
    ]

    operations = [
    ]
