# Generated by Django 2.0.6 on 2019-03-11 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_merge_20190311_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 11, 22, 25, 52, 293698, tzinfo=utc)),
        ),
    ]
