# Generated by Django 2.0.6 on 2019-03-11 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190311_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 11, 22, 26, 29, 656729, tzinfo=utc)),
        ),
    ]
