# Generated by Django 2.0.6 on 2019-03-12 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190311_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 12, 13, 28, 6, 288451, tzinfo=utc)),
        ),
    ]
