# Generated by Django 2.0.6 on 2019-03-18 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190314_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 18, 16, 38, 49, 362435, tzinfo=utc)),
        ),
    ]
